DATASET_CONFIG: "/home/ph/Desktop/PointCloud/utils_my/kitti/cfg/kitti_dataset.yaml"
CLASS_NAMES: [ 'Car'] # 'Pedestrian', 'Cyclist'
BATCH: 4
EPOCHS: 50

MODEL:
  NAME: SECOND
  CONFIG: "/home/ph/Desktop/PointCloud/utils_my/basic/model/model_cfg/second.yaml"

OPTIMIZER:
  NAME: Adam
  LR: 0.003

